### ISSUE TITLE
nexus3 树莓派4B 4G版本可以用吗？

### ISSUE THREAD

**Issue by Loongle** [pi4k8s/pi4images#2]

**Comment by Loongle** [comment]
镜像Build的时候出现了这个错误 
![image](https://user-images.githubusercontent.com/7290992/150831693-6f97e485-f8bd-4d1a-b80f-d136d7c5de0c.png)

**Comment by fastjrun** [comment]
https://hub.docker.com/r/pi4k8s/nexus3/tags 这个下面的镜像都可以在树莓派4B版本直接用，build的时候因为网络的原因，nexus-*.tar.gz这个包可能无法顺利下载会报错。
nexus镜像我以后不会更新了，我推荐用这个 klo2k/nexus3:3.37.1-01，这个和官方的基本一致，略低几个小版本号而已
